### ISSUE TITLE
轮播图没做点击事件，体验不友好

### ISSUE THREAD

**Issue by MomFeng** [mtjsoft/wanandroid#2]

**Comment by mtjsoft** [comment]
不是已经在“README.md”说过了吗？个人的小程序不支持打开外部链接，轮播图详情也是外链，点击了也打不开啊。想打开外链的话，得自己注册一个小程序企业账号。
声明一下：这个暂时个人的小程序入门练习项目，不是正式上线的产品，所以有些细节还没处理好。等我的个体户账户注册好了，再把所有的点击外链加上。优化是持续的。。。

**Comment by mtjsoft** [comment]
.
